"""These tests were generated by Claude Sonnet 5."""

from __future__ import annotations

import math

import pytest

from dracool.constants import CONSTANTS
from dracool.fetch import load_fixture_buildings
from dracool.heights import (
    HeightSource,
    parse_height,
    parse_levels,
    provenance,
    resolve_frame,
    resolve_height,
)


STOREY = CONSTANTS.heights.storey_height_m
DEFAULT = CONSTANTS.heights.default_height_m


@pytest.mark.parametrize(
    ("raw", "expected"),
    [
        ("12", 12.0),
        ("12.5", 12.5),
        ("12 m", 12.0),
        ("12m", 12.0),
        ("  9  ", 9.0),
        ("40 ft", 40 * 0.3048),
        ("40'", 40 * 0.3048),
    ],
)
def test_parse_height_accepts_real_tag_shapes(raw: str, expected: float) -> None:
    assert parse_height(raw) == pytest.approx(expected)


@pytest.mark.parametrize(
    "raw",
    [None, float("nan"), "", "   ", "tall", "12-14", "0", "-3", "100000"],
)
def test_parse_height_rejects_the_unusable(raw: object) -> None:
    assert parse_height(raw) is None


@pytest.mark.parametrize(("raw", "expected"), [("3", 3.0), ("3.5", 3.5), ("2;3", 3.0)])
def test_parse_levels(raw: str, expected: float) -> None:
    assert parse_levels(raw) == pytest.approx(expected)


@pytest.mark.parametrize("raw", [None, float("nan"), "", "many", "0", "3 m"])
def test_parse_levels_rejects_the_unusable(raw: object) -> None:
    assert parse_levels(raw) is None


# Section 7: height tag, then building:levels, then a type default, then a global one.
def test_the_chain_prefers_an_explicit_height() -> None:
    tags = {"height": "20", "building:levels": "3", "building": "house"}
    assert resolve_height(tags).meters == pytest.approx(20.0)
    assert resolve_height(tags).source is HeightSource.TAG


def test_levels_beat_the_type_default() -> None:
    height = resolve_height({"building:levels": "4", "building": "house"})
    assert height.meters == pytest.approx(4 * STOREY)
    assert height.source is HeightSource.LEVELS


def test_type_default_when_nothing_measured() -> None:
    height = resolve_height({"building": "apartments"})
    assert height.meters == pytest.approx(CONSTANTS.heights.by_building_type_m["apartments"])
    assert height.source is HeightSource.TYPE


@pytest.mark.parametrize("building", ["yes", "nonsense", None])
def test_global_default_for_unknown_types(building: str | None) -> None:
    height = resolve_height({"building": building})
    assert height.meters == pytest.approx(DEFAULT)
    assert height.source is HeightSource.DEFAULT


def test_an_unusable_height_tag_falls_through_rather_than_failing() -> None:
    height = resolve_height({"height": "very tall", "building:levels": "5"})
    assert height.meters == pytest.approx(5 * STOREY)
    assert height.source is HeightSource.LEVELS


def test_resolve_frame_on_the_fixture() -> None:
    resolved = resolve_frame(load_fixture_buildings())
    assert {"height_m", "height_source"} <= set(resolved.columns)
    assert len(resolved) == len(load_fixture_buildings())
    assert (resolved["height_m"] > 0).all()
    assert set(resolved["height_source"]) <= {str(s) for s in HeightSource}


def test_provenance_is_a_distribution() -> None:
    fractions = provenance(resolve_frame(load_fixture_buildings()))
    assert set(fractions) == {str(s) for s in HeightSource}
    assert math.isclose(sum(fractions.values()), 1.0)
    # Section 7's point: the large majority of heights are not measured.
    assert fractions[str(HeightSource.TAG)] < 0.1
