"""These tests were generated by Claude Sonnet 5."""

from __future__ import annotations

import math

import networkx as nx
import numpy as np
import osmnx as ox
import pytest
from shapely.geometry import LineString

from dracool.cities import get_city
from dracool.cost import discounted_cost, edge_cost, sun_exposure
from dracool.crs import to_utm, utm_crs_for
from dracool.fetch import load_fixture_buildings, load_fixture_graph
from dracool.fraction import Occluders, fraction_raycast
from dracool.heights import resolve_frame
from dracool.solar import SunPosition


SUN = SunPosition(altitude_deg=25.0, azimuth_deg=140.0)


# Proposition 3 (i): the multiplier is at least 1, so no edge is cheaper than
# its own length and Dijkstra applies.
@pytest.mark.parametrize("w", [0.0, 0.2, 1.0, 5.0])
@pytest.mark.parametrize("sigma", [0.0, 0.25, 0.5, 1.0])
def test_cost_is_never_below_length(w: float, sigma: float) -> None:
    assert edge_cost(100.0, sigma, w) >= 100.0 >= 0.0


def test_w_zero_is_the_ordinary_shortest_path() -> None:
    for sigma in (0.0, 0.5, 1.0):
        assert edge_cost(100.0, sigma, 0.0) == 100.0


def test_the_multiplier_spans_one_to_one_plus_w() -> None:
    assert edge_cost(100.0, 1.0, 0.75) == pytest.approx(100.0), "fully shaded"
    assert edge_cost(100.0, 0.0, 0.75) == pytest.approx(175.0), "fully exposed"


def test_sun_exposure_ignores_w() -> None:
    lengths = np.array([100.0, 50.0])
    sigmas = np.array([0.25, 1.0])
    assert sun_exposure(lengths, sigmas) == pytest.approx(75.0)


# The rejected form of Section 6.2, in the small: its multiplier is below 1.
def test_the_discounted_form_can_cost_less_than_its_length() -> None:
    assert discounted_cost(100.0, 1.0, 0.5) == pytest.approx(50.0)


@pytest.fixture(scope="module")
def graph() -> tuple[nx.MultiDiGraph, dict[int, tuple[float, float]]]:
    """The fixture graph, projected, with a real sigma on every edge."""
    city = get_city("tbilisi")
    buildings = to_utm(resolve_frame(load_fixture_buildings()), city).reset_index(drop=True)
    projected = ox.project_graph(load_fixture_graph(), to_crs=utm_crs_for(buildings))

    # Routing needs somewhere to route to, so work in the largest component.
    largest = max(nx.strongly_connected_components(projected), key=len)
    graph = projected.subgraph(largest).copy()

    occluders = Occluders.from_frame(buildings)
    for u, v, data in graph.edges(data=True):
        geometry = data.get("geometry")
        if geometry is None:
            geometry = LineString(
                [
                    (graph.nodes[u]["x"], graph.nodes[u]["y"]),
                    (graph.nodes[v]["x"], graph.nodes[v]["y"]),
                ]
            )
        data["sigma"] = fraction_raycast(geometry, occluders, SUN)
        data["length_m"] = float(geometry.length)

    positions = {n: (d["x"], d["y"]) for n, d in graph.nodes(data=True)}
    return graph, positions


def _apply(graph: nx.MultiDiGraph, w: float, discounted: bool = False) -> None:
    formula = discounted_cost if discounted else edge_cost
    for _, _, data in graph.edges(data=True):
        data["cost"] = formula(data["length_m"], data["sigma"], w)


def _pairs(graph: nx.MultiDiGraph, count: int = 12) -> list[tuple[int, int]]:
    nodes = sorted(graph.nodes)
    rng = np.random.default_rng(7)
    picked = rng.choice(len(nodes), size=(count, 2), replace=True)
    return [(nodes[a], nodes[b]) for a, b in picked if a != b]


# Proposition 3 (ii) and (iii), tested the way they are actually used: A* with
# the Euclidean heuristic must return the same cost as Dijkstra, which has no
# heuristic to be wrong about.
@pytest.mark.parametrize("w", [0.0, 0.2, 1.0, 3.0])
def test_astar_matches_dijkstra(graph, w: float) -> None:
    g, positions = graph
    _apply(g, w)

    def heuristic(node: int, target: int) -> float:
        return math.dist(positions[node], positions[target])

    for source, target in _pairs(g):
        try:
            optimal = nx.dijkstra_path_length(g, source, target, weight="cost")
        except nx.NetworkXNoPath:
            continue
        found = nx.astar_path_length(g, source, target, heuristic=heuristic, weight="cost")
        assert found == pytest.approx(optimal, rel=1e-9), f"A* was suboptimal at w={w}"


def _inadmissible_nodes(graph: nx.MultiDiGraph, positions: dict, target: int) -> list[int]:
    """Nodes where straight-line distance overestimates the true cost to target."""
    reach = nx.single_source_dijkstra_path_length(graph.reverse(copy=True), target, weight="cost")
    return [
        node
        for node, true_cost in reach.items()
        if math.dist(positions[node], positions[target]) > true_cost + 1e-6
    ]


# Proposition 3 (ii) directly: h(v) <= h*(v) for every node.
def test_the_heuristic_never_overestimates(graph) -> None:
    g, positions = graph
    _apply(g, 1.0)
    target = sorted(g.nodes)[0]
    assert _inadmissible_nodes(g, positions, target) == []


# And Section 6.2's argument, made executable. Under the discounted form a
# path can cost less than its own length, so straight-line distance stops
# being a lower bound and A* is no longer entitled to stop when it does.
def test_the_rejected_form_destroys_admissibility(graph) -> None:
    g, positions = graph
    _apply(g, 0.8, discounted=True)
    target = sorted(g.nodes)[0]
    broken = _inadmissible_nodes(g, positions, target)
    assert broken, "c' should make the Euclidean heuristic inadmissible, and does"
