"""These tests were generated by Claude Sonnet 5."""
from __future__ import annotations

from dataclasses import replace

import geopandas as gpd
import pytest
import shapely

from tenshadows.cities import get_city
from tenshadows.crs import require_wgs84, to_utm, to_wgs84, utm_crs_for
from tenshadows.fetch import load_fixture_buildings


TBILISI = get_city("tbilisi")


@pytest.fixture(scope="module")
def buildings() -> gpd.GeoDataFrame:
    return load_fixture_buildings()


# Section 2.2 names the zones: Tbilisi 38N, Saarbruecken 32N.
def test_fixture_lands_in_the_declared_zone(buildings: gpd.GeoDataFrame) -> None:
    assert utm_crs_for(buildings).to_epsg() == TBILISI.expected_utm_epsg == 32638


def test_a_wrong_declared_zone_is_caught(buildings: gpd.GeoDataFrame) -> None:
    wrong = replace(TBILISI, expected_utm_epsg=32632)
    with pytest.raises(ValueError, match="EPSG:32632"):
        utm_crs_for(buildings, wrong)


def test_round_trip_returns_the_original_coordinates(buildings: gpd.GeoDataFrame) -> None:
    back = to_wgs84(to_utm(buildings, TBILISI))
    assert back.crs.to_epsg() == 4326
    # Vertex by vertex, not via representative_point(): that is recomputed from
    # whatever polygon it is handed, so it moves for reasons unrelated to the
    # projection and would make this test measure the wrong thing.
    original = shapely.get_coordinates(buildings.geometry.to_numpy())
    returned = shapely.get_coordinates(back.geometry.to_numpy())
    assert original.shape == returned.shape
    assert original == pytest.approx(returned, abs=1e-11)


# The whole reason for projecting: areas and distances must come out in metres.
def test_projected_units_are_metres(buildings: gpd.GeoDataFrame) -> None:
    projected = to_utm(buildings, TBILISI)
    assert projected.crs.axis_info[0].unit_name == "metre"
    # A city block of buildings, so areas belong somewhere in this range.
    assert 10.0 < projected.geometry.area.median() < 10_000.0


def test_require_wgs84_accepts_only_the_export_crs(buildings: gpd.GeoDataFrame) -> None:
    assert require_wgs84(buildings) is buildings
    with pytest.raises(ValueError, match="EPSG:4326"):
        require_wgs84(to_utm(buildings, TBILISI))
    with pytest.raises(ValueError, match="no CRS"):
        require_wgs84(buildings.set_crs(None, allow_override=True))
