"""These tests were generated by Claude Sonnet 5."""

from __future__ import annotations

import json
from dataclasses import replace
from pathlib import Path
from typing import Any

import geopandas as gpd
import pytest
from pyproj import Geod
from shapely.geometry import LineString

from tenshadows.cities import get_city
from tenshadows.crs import to_utm
from tenshadows.export import COORD_DECIMALS, HEIGHT_CODES, export_city
from tenshadows.fetch import load_fixture_buildings, load_fixture_graph
from tenshadows.graph import StreetGraph, oriented, street_graph
from tenshadows.heights import resolve_frame


TBILISI = get_city("tbilisi")
GEOD = Geod(ellps="WGS84")


@pytest.fixture(scope="module")
def buildings() -> gpd.GeoDataFrame:
    return resolve_frame(load_fixture_buildings())


@pytest.fixture(scope="module")
def streets() -> StreetGraph:
    return street_graph(load_fixture_graph(), TBILISI)


@pytest.fixture(scope="module")
def artifacts(
    tmp_path_factory: pytest.TempPathFactory, streets: StreetGraph, buildings: gpd.GeoDataFrame
) -> Path:
    return export_city(TBILISI, streets, buildings, tmp_path_factory.mktemp("mini"))


def _json(artifacts: Path, name: str) -> dict[str, Any]:
    return json.loads((artifacts / name).read_text(encoding="utf-8"))


def test_the_three_artifacts_are_written(artifacts: Path) -> None:
    assert sorted(p.name for p in artifacts.iterdir()) == [
        "buildings.geojson",
        "graph.json",
        "meta.json",
    ]


# Section 2.2 is a hard rule, so the point of these two is that breaking it
# fails here rather than putting degrees where the client expects them.
def test_projected_buildings_are_refused(
    tmp_path: Path, streets: StreetGraph, buildings: gpd.GeoDataFrame
) -> None:
    with pytest.raises(ValueError, match="EPSG:4326"):
        export_city(TBILISI, streets, to_utm(buildings, TBILISI), tmp_path)


def test_a_projected_graph_is_refused(
    tmp_path: Path, streets: StreetGraph, buildings: gpd.GeoDataFrame
) -> None:
    with pytest.raises(ValueError, match="EPSG:4326"):
        export_city(TBILISI, replace(streets, crs="EPSG:32638"), buildings, tmp_path)


def test_the_graph_declares_the_export_crs(artifacts: Path) -> None:
    assert _json(artifacts, "graph.json")["crs"] == "EPSG:4326"


def test_coordinates_are_longitude_then_latitude(artifacts: Path) -> None:
    graph = _json(artifacts, "graph.json")
    coords = graph["edges"]["coords"]
    # Tbilisi. Swapped axes would put the longitudes at 41 and fail both.
    assert all(44.0 < value < 45.0 for value in coords[0::2])
    assert all(41.0 < value < 42.0 for value in coords[1::2])
    assert all(44.0 < value < 45.0 for value in graph["nodes"]["lon"])
    assert all(41.0 < value < 42.0 for value in graph["nodes"]["lat"])


def test_coordinates_are_rounded_to_the_contract(artifacts: Path) -> None:
    graph = _json(artifacts, "graph.json")
    values = graph["edges"]["coords"] + graph["nodes"]["lon"] + graph["nodes"]["lat"]
    assert all(value == round(value, COORD_DECIMALS) for value in values)


def _polyline(graph: dict[str, Any], i: int) -> list[float]:
    """An edge as the client rebuilds it: node u, the interior points, node v."""
    nodes, edges = graph["nodes"], graph["edges"]
    u, v = edges["u"][i], edges["v"][i]
    interior = edges["coords"][edges["geom_offset"][i] : edges["geom_offset"][i + 1]]
    return [nodes["lon"][u], nodes["lat"][u], *interior, nodes["lon"][v], nodes["lat"][v]]


def test_geom_offset_is_a_valid_csr_index(artifacts: Path) -> None:
    edges = _json(artifacts, "graph.json")["edges"]
    offsets = edges["geom_offset"]

    assert len(offsets) == len(edges["u"]) + 1
    assert offsets[0] == 0
    assert offsets[-1] == len(edges["coords"])
    # A slice is a run of lon/lat pairs, empty for a straight edge.
    for start, end in zip(offsets[:-1], offsets[1:], strict=True):
        assert end >= start
        assert (end - start) % 2 == 0


# The endpoints are left out of coords because they are already in the node
# table. That is only true if they really do coincide, which is what the
# fixture's own geometry is checked against here.
def test_the_dropped_endpoints_are_the_nodes(artifacts: Path, streets: StreetGraph) -> None:
    graph = _json(artifacts, "graph.json")
    for i, line in enumerate(streets.geometry):
        original = [value for xy in line.coords for value in xy]
        # 1e-6 degrees is the rounding the contract asks for, and the only
        # difference a correct rebuild can have from the source geometry.
        assert _polyline(graph, i) == pytest.approx(original, abs=1e-6)


def test_straight_edges_carry_no_geometry(artifacts: Path) -> None:
    offsets = _json(artifacts, "graph.json")["edges"]["geom_offset"]
    assert any(end == start for start, end in zip(offsets[:-1], offsets[1:], strict=True))


def test_node_indices_are_in_range(artifacts: Path) -> None:
    graph = _json(artifacts, "graph.json")
    count = len(graph["nodes"]["lon"])
    assert len(graph["nodes"]["lat"]) == count
    assert all(0 <= i < count for i in graph["edges"]["u"] + graph["edges"]["v"])


# len is the l(e) of Proposition 3 and is shipped precisely so the client does
# not have to trust its own approximate projection. Geodesic lengths are an
# independent yardstick: they do not go through our UTM code at all.
def test_edge_lengths_are_metres(artifacts: Path) -> None:
    graph = _json(artifacts, "graph.json")
    edges = graph["edges"]

    for i, length in enumerate(edges["len"]):
        line = _polyline(graph, i)
        geodesic = GEOD.geometry_length(LineString(list(zip(line[0::2], line[1::2], strict=True))))
        # rel covers the UTM scale factor, abs the 11 cm coordinate rounding,
        # which on a short edge is worth more than the projection is.
        assert length == pytest.approx(geodesic, rel=2e-3, abs=0.3)
        assert length > 0.0


def test_buildings_carry_only_the_two_short_properties(artifacts: Path) -> None:
    geojson = _json(artifacts, "buildings.geojson")
    assert geojson["type"] == "FeatureCollection"
    for feature in geojson["features"]:
        assert set(feature["properties"]) == {"h", "hs"}
        assert feature["geometry"]["type"] == "Polygon"
        assert feature["properties"]["h"] > 0.0
        assert feature["properties"]["hs"] in HEIGHT_CODES.values()


def test_counts_describe_what_was_actually_written(artifacts: Path) -> None:
    meta = _json(artifacts, "meta.json")
    graph = _json(artifacts, "graph.json")
    geojson = _json(artifacts, "buildings.geojson")

    assert meta["counts"]["nodes"] == len(graph["nodes"]["lon"])
    assert meta["counts"]["edges"] == len(graph["edges"]["u"])
    assert meta["counts"]["buildings"] == len(geojson["features"])


def test_the_bbox_contains_everything_exported(artifacts: Path) -> None:
    meta = _json(artifacts, "meta.json")
    graph = _json(artifacts, "graph.json")
    minx, miny, maxx, maxy = meta["bbox"]

    assert minx < maxx and miny < maxy
    assert min(graph["nodes"]["lon"]) >= minx and max(graph["nodes"]["lon"]) <= maxx
    assert min(graph["nodes"]["lat"]) >= miny and max(graph["nodes"]["lat"]) <= maxy


# Section 7: a router whose input is largely guesswork should say so, which it
# can only do if the shares travel with the data.
def test_height_provenance_is_a_distribution(artifacts: Path) -> None:
    shares = _json(artifacts, "meta.json")["height_provenance"]
    assert set(shares) == {"tag", "levels", "type", "default"}
    assert sum(shares.values()) == pytest.approx(1.0)


# ODbL, not decoration: a public deployment has to credit OSM on screen.
def test_meta_carries_the_licence_obligation(artifacts: Path) -> None:
    meta = _json(artifacts, "meta.json")
    assert "OpenStreetMap" in meta["attribution"]
    assert meta["data_license"] == "ODbL-1.0"
    assert meta["utm_epsg"] == TBILISI.expected_utm_epsg


def test_oriented_reverses_only_when_it_has_to() -> None:
    line = LineString([(0.0, 0.0), (1.0, 1.0)])
    assert oriented(line, (0.0, 0.0)) is line
    assert list(oriented(line, (1.0, 1.0)).coords) == [(1.0, 1.0), (0.0, 0.0)]
