"""These tests were generated by Claude Sonnet 5."""

from __future__ import annotations

import json

import geopandas as gpd
import numpy as np
import pytest
import shapely
from shapely.geometry import LineString, Polygon

from dracool.cities import get_city
from dracool.constants import CONSTANTS
from dracool.crs import to_utm
from dracool.fetch import load_fixture_buildings
from dracool.fraction import (
    Occluders,
    fraction_exact,
    fraction_raycast,
    fraction_sampled,
    raycast_shaded,
    sample_offsets,
)
from dracool.heights import resolve_frame
from dracool.reference import REFERENCE_DIR, shade_cases
from dracool.shadows import shadow_union
from dracool.solar import SunPosition


DELTA = CONSTANTS.sampling.spacing_m


def sun(altitude_deg: float = 30.0, azimuth_deg: float = 180.0) -> SunPosition:
    return SunPosition(altitude_deg=altitude_deg, azimuth_deg=azimuth_deg)


@pytest.fixture(scope="module")
def buildings() -> gpd.GeoDataFrame:
    frame = resolve_frame(load_fixture_buildings())
    return to_utm(frame, get_city("tbilisi")).reset_index(drop=True)


@pytest.fixture(scope="module")
def patch(buildings: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    """A few hundred real footprints: enough to be messy, small enough to union."""
    return buildings.head(400)


# Section 5.2: m = ceil(l / Delta) points.
@pytest.mark.parametrize(
    ("length", "expected"),
    [(0.0, 1), (1.0, 1), (DELTA, 1), (DELTA + 0.001, 2), (10 * DELTA, 10)],
)
def test_sample_count(length: float, expected: int) -> None:
    assert len(sample_offsets(length)) == expected


def test_samples_sit_inside_the_edge_and_are_evenly_spaced() -> None:
    offsets = sample_offsets(100.0)
    assert offsets.min() > 0.0
    assert offsets.max() < 100.0
    assert np.allclose(np.diff(offsets), offsets[1] - offsets[0])


# Definition 1's two extremes.
def test_a_fully_exposed_edge_is_zero() -> None:
    edge = LineString([(0, 0), (100, 0)])
    empty = Polygon()
    assert fraction_exact(edge, empty, sun()) == 0.0
    assert fraction_sampled(edge, empty, sun()) == 0.0


def test_a_fully_covered_edge_is_one() -> None:
    edge = LineString([(0, 0), (100, 0)])
    everything = shapely.box(-10, -10, 110, 10)
    assert fraction_exact(edge, everything, sun()) == pytest.approx(1.0)
    assert fraction_sampled(edge, everything, sun()) == pytest.approx(1.0)


def test_half_covered_is_one_half() -> None:
    edge = LineString([(0, 0), (100, 0)])
    half = shapely.box(-10, -10, 50, 10)
    assert fraction_exact(edge, half, sun()) == pytest.approx(0.5)
    assert fraction_sampled(edge, half, sun()) == pytest.approx(0.5, abs=DELTA / 100.0)


# Section 3.3 and Definition 1: below the horizon every edge reads as shaded,
# so the cost function degenerates to pure distance rather than to nonsense.
def test_night_is_fully_shaded_whatever_the_geometry() -> None:
    edge = LineString([(0, 0), (100, 0)])
    night = SunPosition(altitude_deg=-0.5, azimuth_deg=180.0)
    assert fraction_exact(edge, Polygon(), night) == 1.0
    assert fraction_sampled(edge, Polygon(), night) == 1.0


# Proposition 2, in the small: a single square building, sun due south. Points
# just north of it are shaded, points south of it are not.
def test_raycast_on_one_building() -> None:
    footprint = shapely.box(0, 0, 10, 10)
    frame = gpd.GeoDataFrame({"height_m": [10.0]}, geometry=[footprint], crs=32638)
    occluders = Occluders.from_frame(frame)
    low = sun(45.0)  # L = 10 m, so shadow reaches y = 20

    xs = np.array([5.0, 5.0, 5.0, 5.0])
    ys = np.array([15.0, 19.0, 21.0, 40.0])
    assert list(raycast_shaded(xs, ys, occluders, low)) == [True, True, False, False]

    # And nothing south of the building is ever shaded by it.
    assert not raycast_shaded(np.array([5.0]), np.array([-5.0]), occluders, low)[0]


def test_raycast_respects_the_buildings_own_height() -> None:
    footprint = shapely.box(0, 0, 10, 10)
    tall = Occluders.from_frame(gpd.GeoDataFrame({"height_m": [30.0]}, geometry=[footprint]))
    short = Occluders.from_frame(gpd.GeoDataFrame({"height_m": [2.0]}, geometry=[footprint]))
    at = sun(45.0)
    xs, ys = np.array([5.0]), np.array([25.0])
    assert raycast_shaded(xs, ys, tall, at)[0], "a 30 m building reaches 30 m north"
    assert not raycast_shaded(xs, ys, short, at)[0], "a 2 m one does not"


# The claim the whole client architecture rests on. If these disagree, either
# Proposition 2 is misimplemented or the sweep is.
@pytest.mark.parametrize("altitude_deg", [12.0, 30.0, 60.0])
@pytest.mark.parametrize("azimuth_deg", [0.0, 95.0, 180.0, 285.0])
def test_raycast_agrees_with_polygon_membership(
    patch: gpd.GeoDataFrame, altitude_deg: float, azimuth_deg: float
) -> None:
    at = sun(altitude_deg, azimuth_deg)
    union = shadow_union(patch, at)
    occluders = Occluders.from_frame(patch)

    rng = np.random.default_rng(0)
    minx, miny, maxx, maxy = patch.total_bounds
    xs = rng.uniform(minx, maxx, 400)
    ys = rng.uniform(miny, maxy, 400)

    by_ray = raycast_shaded(xs, ys, occluders, at)
    by_polygon = shapely.intersects_xy(union, xs, ys)

    disagreements = int(np.sum(by_ray != by_polygon))
    assert disagreements == 0, f"{disagreements}/400 points disagree at a={altitude_deg}"


def test_the_three_estimators_agree_on_real_edges(patch: gpd.GeoDataFrame) -> None:
    at = sun(25.0, 135.0)
    union = shadow_union(patch, at)
    occluders = Occluders.from_frame(patch)

    minx, miny, maxx, maxy = patch.total_bounds
    rng = np.random.default_rng(1)
    edges = [
        LineString(
            [
                (rng.uniform(minx, maxx), rng.uniform(miny, maxy)),
                (rng.uniform(minx, maxx), rng.uniform(miny, maxy)),
            ]
        )
        for _ in range(40)
    ]

    for edge in edges:
        exact = fraction_exact(edge, union, at)
        sampled = fraction_sampled(edge, union, at)
        cast = fraction_raycast(edge, occluders, at)

        assert sampled == cast, "the two estimators must make identical decisions"
        # Section 5.2 bounds the sampling error by Delta * crossings / length.
        assert abs(sampled - exact) < 0.5
        assert 0.0 <= exact <= 1.0 and 0.0 <= sampled <= 1.0


def test_sampling_converges_on_the_exact_value(patch: gpd.GeoDataFrame) -> None:
    at = sun(20.0, 200.0)
    union = shadow_union(patch, at)
    minx, miny, maxx, maxy = patch.total_bounds
    edge = LineString([(minx, (miny + maxy) / 2), (maxx, (miny + maxy) / 2)])

    exact = fraction_exact(edge, union, at)
    coarse = float(np.mean(shapely.intersects_xy(union, *_xy(edge, 25.0))))
    fine = float(np.mean(shapely.intersects_xy(union, *_xy(edge, 0.25))))
    assert abs(fine - exact) <= abs(coarse - exact) + 1e-9


def _xy(edge: LineString, spacing: float) -> tuple[np.ndarray, np.ndarray]:
    points = shapely.line_interpolate_point(edge, sample_offsets(edge.length, spacing))
    return shapely.get_x(points), shapely.get_y(points)


# The scene the browser suite asserts against. It is self-contained: metric
# coordinates, footprints, heights and edges all travel in the one file.
def test_committed_reference_scene_is_current() -> None:
    path = REFERENCE_DIR / "shade_mini.json"
    assert path.is_file(), "run `python -m dracool.reference`"
    committed = json.loads(path.read_text(encoding="utf-8"))
    committed.pop("_comment", None)
    assert committed == shade_cases(), "the reference scene is stale, regenerate it"


def test_the_reference_scene_covers_the_cases_that_matter() -> None:
    scene = shade_cases()
    labels = {s["label"] for s in scene["suns"]}
    assert {"capped", "low", "high", "night"} <= labels
    night = [s["label"] for s in scene["suns"]].index("night")
    assert all(edge["sigma"][night] == 1.0 for edge in scene["edges"]), "Definition 1 at night"
