"""These tests are generated by Claude Sonnet 5."""

from __future__ import annotations

import json
import math
from datetime import UTC, datetime

import pytest
import suncalc

from dracool.cities import all_cities
from dracool.reference import REFERENCE_DIR, solar_cases
from dracool.solar import SunPosition, sun_position


SYDNEY = (-33.8688, 151.2093)


# times=() asks for nothing but the meridian crossing, which is all this needs.
# The default set includes astronomical twilight, and above roughly 48 degrees in
# midsummer the sun never gets 18 degrees below the horizon, so suncalc takes the
# arccos of something outside [-1, 1] and warns on a value we never read.
def _solar_noon(lat: float, lon: float, year: int, month: int, day: int) -> datetime:
    times = suncalc.get_times(datetime(year, month, day, tzinfo=UTC), lon, lat, times=())
    noon = times["solar_noon"]
    return noon.replace(tzinfo=UTC) if noon.tzinfo is None else noon


# Section 3.2 states this check outright: a sun on the eastern horizon points due east.
def test_eastern_horizon_points_east() -> None:
    x, y, z = SunPosition(altitude_deg=0.0, azimuth_deg=90.0).direction
    assert (pytest.approx(x), pytest.approx(y), pytest.approx(z)) == (1.0, 0.0, 0.0)


# And the other check: a sun due south has horizontal part (0, -cos a).
@pytest.mark.parametrize("altitude_deg", [0.0, 15.0, 45.0, 89.0])
def test_due_south_points_south(altitude_deg: float) -> None:
    sun = SunPosition(altitude_deg=altitude_deg, azimuth_deg=180.0)
    x, y, _ = sun.direction
    assert x == pytest.approx(0.0, abs=1e-12)
    assert y == pytest.approx(-math.cos(math.radians(altitude_deg)))
    assert sun.horizontal_direction == pytest.approx((0.0, -1.0), abs=1e-12)


@pytest.mark.parametrize("altitude_deg", [-10.0, 0.0, 30.0, 75.0, 90.0])
@pytest.mark.parametrize("azimuth_deg", [0.0, 45.0, 137.0, 270.0, 359.0])
def test_direction_vectors_are_unit(altitude_deg: float, azimuth_deg: float) -> None:
    sun = SunPosition(altitude_deg=altitude_deg, azimuth_deg=azimuth_deg)
    assert math.hypot(*sun.direction[:2], sun.direction[2]) == pytest.approx(1.0)
    assert math.hypot(*sun.horizontal_direction) == pytest.approx(1.0)


# Section 2.3: altitude sets shadow length, azimuth sets direction. They are independent.
def test_horizontal_direction_ignores_altitude() -> None:
    at_dawn = SunPosition(altitude_deg=1.0, azimuth_deg=137.0).horizontal_direction
    at_noon = SunPosition(altitude_deg=80.0, azimuth_deg=137.0).horizontal_direction
    assert at_dawn == pytest.approx(at_noon)


# Remark 2. Without the south-to-north conversion these two land 180 degrees out,
# which rotates every shadow in the city and raises nothing.
def test_northern_solar_noon_is_due_south() -> None:
    for city in all_cities():
        noon = _solar_noon(city.center_lat, city.center_lon, 2026, 6, 21)
        sun = sun_position(noon, lat=city.center_lat, lon=city.center_lon)
        assert sun.azimuth_deg == pytest.approx(180.0, abs=1.0), city.key


def test_southern_solar_noon_is_due_north() -> None:
    lat, lon = SYDNEY
    noon = _solar_noon(lat, lon, 2026, 6, 21)
    sun = sun_position(noon, lat=lat, lon=lon)
    # Due north is 0 and 360 at once, so compare on the circle.
    assert min(sun.azimuth_deg, 360.0 - sun.azimuth_deg) == pytest.approx(0.0, abs=1.0)


def test_azimuth_is_within_one_turn() -> None:
    for case in solar_cases():
        assert 0.0 <= case["azimuth_deg"] < 360.0
        assert -90.0 <= case["altitude_deg"] <= 90.0


def test_naive_datetime_is_rejected() -> None:
    with pytest.raises(ValueError, match="timezone-aware"):
        sun_position(datetime(2026, 6, 21, 12, 0), lat=41.6941, lon=44.8336)


# Section 3.3: below the horizon the shade term carries no information.
def test_night_matches_the_sunset_threshold() -> None:
    assert SunPosition(altitude_deg=-0.5, azimuth_deg=0.0).is_night
    assert SunPosition(altitude_deg=0.0, azimuth_deg=0.0).is_night
    assert not SunPosition(altitude_deg=0.5, azimuth_deg=0.0).is_night


def test_sun_is_below_horizon_at_local_midnight() -> None:
    # Tbilisi is UTC+4, so 20:00 UTC is local midnight.
    sun = sun_position(datetime(2026, 6, 21, 20, 0, tzinfo=UTC), lat=41.6941, lon=44.8336)
    assert sun.is_night


# The committed reference values are what the browser suite asserts against, so a
# drift between them and the code would let the two languages diverge unnoticed.
def test_committed_reference_is_current() -> None:
    path = REFERENCE_DIR / "solar.json"
    assert path.is_file(), "run `python -m dracool.reference`"
    committed = json.loads(path.read_text(encoding="utf-8"))["cases"]
    assert committed == solar_cases(), "reference values are stale, regenerate them"
