"""These tests were generated by Claude Sonnet 5."""

from __future__ import annotations

import json
import math

import geopandas as gpd
import pytest
import shapely
from shapely.geometry import MultiPoint, Polygon

from dracool.cities import get_city
from dracool.constants import CONSTANTS
from dracool.crs import to_utm
from dracool.fetch import load_fixture_buildings
from dracool.heights import resolve_frame
from dracool.reference import REFERENCE_DIR, shadow_cases
from dracool.shadows import (
    building_shadow,
    shadow_displacement,
    shadow_length,
    shadow_union,
    sweep,
)
from dracool.solar import SunPosition


A_MIN = CONSTANTS.solar.min_altitude_deg
L_MAX = CONSTANTS.shadow.max_length_m

# An L, so it has a re-entrant corner. Remark 3 is about exactly this shape.
L_SHAPE = Polygon([(0, 0), (10, 0), (10, 4), (4, 4), (4, 10), (0, 10)])
SQUARE = Polygon([(0, 0), (10, 0), (10, 10), (0, 10)])


def noon(altitude_deg: float = 45.0) -> SunPosition:
    return SunPosition(altitude_deg=altitude_deg, azimuth_deg=180.0)


# The specification hands us this one: with the sun due south the shadow points
# due north. It catches a flipped sign and a swapped azimuth convention at once.
def test_a_southern_sun_throws_the_shadow_north() -> None:
    dx, dy = shadow_displacement(10.0, noon(45.0))
    assert dx == pytest.approx(0.0, abs=1e-12)
    assert dy == pytest.approx(10.0)


@pytest.mark.parametrize("azimuth_deg", [0.0, 90.0, 180.0, 270.0, 37.0])
def test_displacement_is_antiparallel_to_the_sun(azimuth_deg: float) -> None:
    sun = SunPosition(altitude_deg=30.0, azimuth_deg=azimuth_deg)
    d = shadow_displacement(12.0, sun)
    u = sun.horizontal_direction
    assert math.hypot(*d) == pytest.approx(shadow_length(12.0, sun))
    # Antiparallel: the dot product is exactly minus the length.
    assert d[0] * u[0] + d[1] * u[1] == pytest.approx(-math.hypot(*d))


@pytest.mark.parametrize("altitude_deg", [10.0, 30.0, 45.0, 60.0, 80.0])
def test_length_is_height_over_tan(altitude_deg: float) -> None:
    expected = 10.0 / math.tan(math.radians(altitude_deg))
    assert shadow_length(10.0, noon(altitude_deg)) == pytest.approx(expected)


def test_overhead_sun_casts_almost_nothing() -> None:
    assert shadow_length(10.0, noon(90.0)) == pytest.approx(0.0, abs=1e-14)


# Section 3.3, and note the cap is conditional on a < a_min.
def test_low_sun_is_capped() -> None:
    assert shadow_length(50.0, noon(1.0)) == pytest.approx(L_MAX)
    assert shadow_length(0.5, noon(1.0)) < L_MAX, "a short building stays under the cap"


def test_the_cap_does_not_apply_above_a_min() -> None:
    just_above = shadow_length(50.0, noon(A_MIN + 0.001))
    assert just_above > L_MAX, "the specification caps only below a_min"


def test_night_is_refused() -> None:
    with pytest.raises(ValueError, match="below the horizon"):
        shadow_length(10.0, SunPosition(altitude_deg=-1.0, azimuth_deg=180.0))


# Remark 3. If this ever passes, someone has replaced the sweep with a hull.
def test_the_sweep_is_not_the_convex_hull() -> None:
    dx, dy = shadow_displacement(10.0, noon(45.0))
    swept = sweep(L_SHAPE, dx, dy)
    moved = shapely.affinity.translate(L_SHAPE, dx, dy)
    hull = MultiPoint(list(L_SHAPE.exterior.coords) + list(moved.exterior.coords)).convex_hull
    assert swept.area < hull.area, "the hull reports shade over a corner that is sunlit"
    assert swept.within(hull), "and it does so by adding area, never removing it"


def test_the_sweep_contains_both_ends() -> None:
    dx, dy = shadow_displacement(10.0, noon(45.0))
    swept = sweep(L_SHAPE, dx, dy)
    assert L_SHAPE.within(swept.buffer(1e-9))
    assert shapely.affinity.translate(L_SHAPE, dx, dy).within(swept.buffer(1e-9))


# For a convex footprint the swept area is exactly area(B) + |d| * width, where
# width is measured perpendicular to d. A square swept due north gives s^2 + s*L.
def test_swept_area_of_a_square_is_exact() -> None:
    length = shadow_length(10.0, noon(45.0))
    swept = sweep(SQUARE, *shadow_displacement(10.0, noon(45.0)))
    assert swept.area == pytest.approx(100.0 + 10.0 * length)


def test_a_hole_is_swept_too() -> None:
    ring = Polygon(
        [(0, 0), (30, 0), (30, 30), (0, 30)],
        holes=[[(10, 10), (20, 10), (20, 20), (10, 20)]],
    )
    swept = sweep(ring, 0.0, 5.0)
    # The courtyard's southern strip is shaded by its own northern wall.
    assert swept.contains(shapely.Point(15, 12))
    # But the middle of the courtyard, further from that wall, is not.
    assert not swept.contains(shapely.Point(15, 18))


def test_zero_displacement_returns_the_footprint() -> None:
    assert sweep(L_SHAPE, 0.0, 0.0) is L_SHAPE


def test_committed_reference_is_current() -> None:
    path = REFERENCE_DIR / "shadow_points.json"
    assert path.is_file(), "run `python -m dracool.reference`"
    committed = json.loads(path.read_text(encoding="utf-8"))["cases"]
    assert committed == shadow_cases(), "reference values are stale, regenerate them"


@pytest.fixture(scope="module")
def projected() -> gpd.GeoDataFrame:
    buildings = resolve_frame(load_fixture_buildings())
    return to_utm(buildings, get_city("tbilisi"))


def test_real_footprints_produce_valid_shadows(projected: gpd.GeoDataFrame) -> None:
    sun = noon(35.0)
    sample = projected.head(200)
    for geom, height in zip(sample.geometry, sample["height_m"], strict=True):
        shadow = building_shadow(geom, height, sun)
        assert shadow.is_valid
        assert shadow.area >= geom.area - 1e-6, "a shadow includes the footprint it comes from"


# Section 5.1: union first, then measure. Overlapping shadows must not be
# double counted, so the union is strictly smaller than the sum of the parts.
def test_the_union_deduplicates_overlap(projected: gpd.GeoDataFrame) -> None:
    sample = projected.head(300)
    sun = noon(20.0)
    union = shadow_union(sample, sun)
    separate = sum(
        building_shadow(g, h, sun).area
        for g, h in zip(sample.geometry, sample["height_m"], strict=True)
    )
    assert union.area < separate, "adjacent buildings on a narrow street overlap heavily"
    assert union.is_valid
