from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Final

from tenshadows.cities import all_cities
from tenshadows.solar import sun_position


# Section 3 and Section 5 are implemented twice, here and in the browser. This
# records what the Python implementation answers, so the JavaScript suite can
# assert it answers the same. Not tests: the output is a committed artifact
# consumed by another language.
#
# The inputs below are fixed rather than sampled, for two reasons. The two
# implementations can only be compared if both are asked the same question, so
# the timestamps and places have to be pinned. And a fixed grid means any diff
# in the output file is a real change in behaviour, which is what makes
# reviewing that diff worth doing.
REFERENCE_DIR: Final[Path] = Path(__file__).resolve().parents[2] / "fixtures" / "reference"

# Both equinoxes and both solstices, sampled every three hours of UTC. The
# solstices are the extremes of solar declination and the equinoxes the middle,
# so the four dates bracket the year rather than sampling it.
DATES: Final[tuple[tuple[int, int, int], ...]] = (
    (2026, 3, 20),
    (2026, 6, 21),
    (2026, 9, 22),
    (2026, 12, 21),
)
HOURS: Final[tuple[int, ...]] = (0, 3, 6, 9, 12, 15, 18, 21)

# The defined cities are both northern and both mid-latitude. These catch a
# hemisphere sign error, an equatorial one, and a polar one, which those cannot.
EXTRA_SITES: Final[tuple[tuple[str, float, float], ...]] = (
    ("sydney", -33.8688, 151.2093),
    ("quito", -0.1807, -78.4678),
    ("tromso", 69.6492, 18.9553),
)


def _sites() -> list[tuple[str, float, float]]:
    cities = [(c.key, c.center_lat, c.center_lon) for c in all_cities()]
    return sorted(cities + list(EXTRA_SITES))


def solar_cases() -> list[dict[str, Any]]:
    cases: list[dict[str, Any]] = []
    for name, lat, lon in _sites():
        for year, month, day in DATES:
            for hour in HOURS:
                when = datetime(year, month, day, hour, tzinfo=UTC)
                sun = sun_position(when, lat=lat, lon=lon)
                cases.append(
                    {
                        "site": name,
                        "lat": lat,
                        "lon": lon,
                        "utc": when.isoformat().replace("+00:00", "Z"),
                        "altitude_deg": round(sun.altitude_deg, 9),
                        "azimuth_deg": round(sun.azimuth_deg, 9),
                        "direction": [round(v, 9) for v in sun.direction],
                        "horizontal_direction": [round(v, 9) for v in sun.horizontal_direction],
                    }
                )
    return cases


def write_reference(directory: Path | None = None) -> Path:
    target = (directory or REFERENCE_DIR) / "solar.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "_comment": (
            "Generated by `python -m tenshadows.reference`. What the Python pipeline "
            "answers for Section 3, asserted by the browser test suite so the two "
            "implementations cannot drift apart. Angles are degrees, azimuth clockwise "
            "from north. Regenerate deliberately: a change here is a change in behaviour."
        ),
        "cases": solar_cases(),
    }
    target.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return target


if __name__ == "__main__":
    print(write_reference())
